In [1]:
import numpy as np

## Data Types & Attributes

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

In [12]:
arr2 = np.array([[1,2.0,3.3],[4,5,6.5]
                ])
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                 [[10,11,12],[13,14,15],[16,17,18]]])

In [13]:
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
arr.shape

(3,)

In [16]:
arr2.shape

(2, 3)

In [17]:
arr3.shape

(2, 3, 3)

In [18]:
arr.ndim,arr2.ndim,arr3.ndim

(1, 2, 3)

In [19]:
arr.ndim

1

In [20]:
arr.dtype,arr2.dtype,arr3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [21]:
arr.size

3

In [22]:
arr2.size

6

In [23]:
arr3.size

18

In [24]:
import pandas as pd
df = pd.DataFrame(arr2)

In [26]:
df

     0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [31]:
df = df.rename(columns={0:'Day 1/Litres',1:"Day 2/Litres",2:'Day 3/Litres'}, index={0:1,1:2})

In [32]:
df

   Day 1/Litres  Day 2/Litres  Day 3/Litres
1           1.0           2.0           3.3
2           4.0           5.0           6.5

In [33]:
ones = np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
zeros = np.zeros((2,3),dtype=int)

In [35]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
range_arr = np.arange(0,11,2)

In [37]:
range_arr

array([ 0,  2,  4,  6,  8, 10])

In [38]:
rand_arr = np.random.randint(0,11,size=(2,3))

In [39]:
rand_arr

array([[1, 4, 0],
       [6, 6, 3]], dtype=int32)

In [40]:
rand_arr.size

6