In [7]:
import pandas as pd

In [25]:
a_spreadsheet = pd.read_csv("heart.csv")

In [26]:
a_spreadsheet.head(23)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0
10,37,F,NAP,130,211,0,Normal,142,N,0.0,Up,0
11,58,M,ATA,136,164,0,ST,99,Y,2.0,Flat,1
12,39,M,ATA,120,204,0,Normal,145,N,0.0,Up,0
13,49,M,ASY,140,234,0,Normal,140,Y,1.0,Flat,1
14,42,F,NAP,115,211,0,ST,137,N,0.0,Up,0
15,54,F,ATA,120,273,0,Normal,150,N,1.5,Flat,0
16,38,M,ASY,110,196,0,Normal,166,N,0.0,Flat,1
17,43,F,ATA,120,201,0,Normal,165,N,0.0,Up,0
18,60,M,ASY,100,248,0,Normal,125,N,1.0,Flat,1
19,36,M,ATA,120,267,0,Normal,160,N,3.0,Flat,1
20,43,F,TA,100,223,0,Normal,142,N,0.0,Up,0
21,44,M,ATA,120,184,0,Normal,142,N,1.0,Flat,0
22,49,F,ATA,124,201,0,Normal,164,N,0.0,Up,0

In [27]:
a_spreadsheet.index = list(range(1,919))

In [28]:
a_spreadsheet.head(23)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
1,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
2,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
3,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
4,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
5,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
6,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
7,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
8,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
9,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
10,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0
11,37,F,NAP,130,211,0,Normal,142,N,0.0,Up,0
12,58,M,ATA,136,164,0,ST,99,Y,2.0,Flat,1
13,39,M,ATA,120,204,0,Normal,145,N,0.0,Up,0
14,49,M,ASY,140,234,0,Normal,140,Y,1.0,Flat,1
15,42,F,NAP,115,211,0,ST,137,N,0.0,Up,0
16,54,F,ATA,120,273,0,Normal,150,N,1.5,Flat,0
17,38,M,ASY,110,196,0,Normal,166,N,0.0,Flat,1
18,43,F,ATA,120,201,0,Normal,165,N,0.0,Up,0
19,60,M,ASY,100,248,0,Normal,125,N,1.0,Flat,1
20,36,M,ATA,120,267,0,Normal,160,N,3.0,Flat,1
21,43,F,TA,100,223,0,Normal,142,N,0.0,Up,0
22,44,M,ATA,120,184,0,Normal,142,N,1.0,Flat,0
23,49,F,ATA,124,201,0,Normal,164,N,0.0,Up,0

In [29]:
a_spreadsheet.index.name = "Index"

In [30]:
a_spreadsheet.head(23)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Index,,,,,,,,,,,,
1,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
2,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
3,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
4,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
5,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
6,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
7,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
8,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
9,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
10,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0
11,37,F,NAP,130,211,0,Normal,142,N,0.0,Up,0
12,58,M,ATA,136,164,0,ST,99,Y,2.0,Flat,1
13,39,M,ATA,120,204,0,Normal,145,N,0.0,Up,0
14,49,M,ASY,140,234,0,Normal,140,Y,1.0,Flat,1
15,42,F,NAP,115,211,0,ST,137,N,0.0,Up,0
16,54,F,ATA,120,273,0,Normal,150,N,1.5,Flat,0
17,38,M,ASY,110,196,0,Normal,166,N,0.0,Flat,1
18,43,F,ATA,120,201,0,Normal,165,N,0.0,Up,0
19,60,M,ASY,100,248,0,Normal,125,N,1.0,Flat,1
20,36,M,ATA,120,267,0,Normal,160,N,3.0,Flat,1
21,43,F,TA,100,223,0,Normal,142,N,0.0,Up,0
22,44,M,ATA,120,184,0,Normal,142,N,1.0,Flat,0
23,49,F,ATA,124,201,0,Normal,164,N,0.0,Up,0

In [39]:
sheet = a_spreadsheet.sample(frac=1)

In [40]:
sheet

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Index,,,,,,,,,,,,
876,58,F,NAP,120,340,0,Normal,172,N,0.0,Up,0
720,63,M,ASY,130,254,0,LVH,147,N,1.4,Flat,1
677,51,F,ASY,130,305,0,Normal,142,Y,1.2,Flat,1
433,63,M,ASY,170,177,0,Normal,84,Y,2.5,Down,1
347,59,M,ASY,120,0,0,Normal,115,N,0.0,Flat,1
...,...,...,...,...,...,...,...,...,...,...,...,...
140,43,M,ASY,150,247,0,Normal,130,Y,2.0,Flat,1
485,65,M,ASY,134,0,0,Normal,112,Y,1.1,Flat,1
107,48,F,ASY,120,254,0,ST,110,N,0.0,Up,0
814,69,F,TA,140,239,0,Normal,151,N,1.8,Up,0
482,69,M,NAP,140,0,1,ST,118,N,2.5,Down,1

In [43]:
sheet.reset_index(drop=True, inplace=True)

In [44]:
sheet

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,58,F,NAP,120,340,0,Normal,172,N,0.0,Up,0
1,63,M,ASY,130,254,0,LVH,147,N,1.4,Flat,1
2,51,F,ASY,130,305,0,Normal,142,Y,1.2,Flat,1
3,63,M,ASY,170,177,0,Normal,84,Y,2.5,Down,1
4,59,M,ASY,120,0,0,Normal,115,N,0.0,Flat,1
...,...,...,...,...,...,...,...,...,...,...,...,...
913,43,M,ASY,150,247,0,Normal,130,Y,2.0,Flat,1
914,65,M,ASY,134,0,0,Normal,112,Y,1.1,Flat,1
915,48,F,ASY,120,254,0,ST,110,N,0.0,Up,0
916,69,F,TA,140,239,0,Normal,151,N,1.8,Up,0
917,69,M,NAP,140,0,1,ST,118,N,2.5,Down,1

In [45]:
sheet.index = list(range(1,919))

In [46]:
sheet

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
1,58,F,NAP,120,340,0,Normal,172,N,0.0,Up,0
2,63,M,ASY,130,254,0,LVH,147,N,1.4,Flat,1
3,51,F,ASY,130,305,0,Normal,142,Y,1.2,Flat,1
4,63,M,ASY,170,177,0,Normal,84,Y,2.5,Down,1
5,59,M,ASY,120,0,0,Normal,115,N,0.0,Flat,1
...,...,...,...,...,...,...,...,...,...,...,...,...
914,43,M,ASY,150,247,0,Normal,130,Y,2.0,Flat,1
915,65,M,ASY,134,0,0,Normal,112,Y,1.1,Flat,1
916,48,F,ASY,120,254,0,ST,110,N,0.0,Up,0
917,69,F,TA,140,239,0,Normal,151,N,1.8,Up,0
918,69,M,NAP,140,0,1,ST,118,N,2.5,Down,1

In [54]:
sheet

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Cholestrol Rate
1,58,F,NAP,120,340,0,Normal,172,N,0.0,Up,0,NaN
2,63,M,ASY,130,254,0,LVH,147,N,1.4,Flat,1,NaN
3,51,F,ASY,130,305,0,Normal,142,Y,1.2,Flat,1,NaN
4,63,M,ASY,170,177,0,Normal,84,Y,2.5,Down,1,NaN
5,59,M,ASY,120,0,0,Normal,115,N,0.0,Flat,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,43,M,ASY,150,247,0,Normal,130,Y,2.0,Flat,1,NaN
915,65,M,ASY,134,0,0,Normal,112,Y,1.1,Flat,1,NaN
916,48,F,ASY,120,254,0,ST,110,N,0.0,Up,0,NaN
917,69,F,TA,140,239,0,Normal,151,N,1.8,Up,0,NaN
918,69,M,NAP,140,0,1,ST,118,N,2.5,Down,1,NaN

In [57]:
sheet["Cholesterol Rate"] = sheet["Cholesterol"].apply(lambda x:x/1.6)

In [58]:
sheet

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Cholestrol Rate,Cholesterol Rate
1,58,F,NAP,120,340,0,Normal,172,N,0.0,Up,0,212.500,212.500
2,63,M,ASY,130,254,0,LVH,147,N,1.4,Flat,1,158.750,158.750
3,51,F,ASY,130,305,0,Normal,142,Y,1.2,Flat,1,190.625,190.625
4,63,M,ASY,170,177,0,Normal,84,Y,2.5,Down,1,110.625,110.625
5,59,M,ASY,120,0,0,Normal,115,N,0.0,Flat,1,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914,43,M,ASY,150,247,0,Normal,130,Y,2.0,Flat,1,154.375,154.375
915,65,M,ASY,134,0,0,Normal,112,Y,1.1,Flat,1,0.000,0.000
916,48,F,ASY,120,254,0,ST,110,N,0.0,Up,0,158.750,158.750
917,69,F,TA,140,239,0,Normal,151,N,1.8,Up,0,149.375,149.375
918,69,M,NAP,140,0,1,ST,118,N,2.5,Down,1,0.000,0.000